services:
    n8n:
      image: n8nio/n8n
      restart: unless-stopped
      ports:
        - "5678:5678"
      environment:
        - N8N_PUSH_BACKEND=sse
        - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
        - N8N_CUSTOM_EXTENSIONS=/custom_nodes
        - N8N_RUNNERS_ENABLED=true
      volumes:
        - ./n8n_data:/home/node/.n8n
        - ./n8n_data/custom_nodes:/custom_nodes
volumes:
  n8n_data: